#defaults:
hydra:
  run:
    dir: ./

model:
  pretrained: true
  out_dim: 1
  in_dim: 1
  ensemble: True
  dropout_rate: 0.3

training:
  warmup_epochs: 0
  weight_identity: 10
  weight_cycle: 3
  samples_per_epoch: 1536
  max_epochs: 100
  batch_size: 8
  optimizer:
    name: adam
    lr: 0.001
  early_stopping:
    monitor: 'loss_sum'
    stopping_patience: 100
  model_checkpoint:
    monitor: 'loss_sum'
data:
  size: 128
  url: 'https://drive.google.com/uc?id=1jPelB2jzNZJq3ZU9Uk_Mkt4MJtF3DRgg'
  path: './data/'
  train_augmentation: []
overlap: 0.2
